# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Private', '0002_auto_20170320_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLoginForm',
            new_name='Registration',
        ),
    ]
